#!/bin/bash

Usage() {
        echo ‘Usage: WIN_dsi_trk_loop <subject list>’
        exit 0
}

[ ‘$1’ = ‘’ ] && Usage

# Subject list for loop
subs=`cat ${1}`          # make sure txt file is full fib file names

projdir=‘/Users/zaz3744/Documents/current_projects/dti_BrainMAPD/src’

cd ${projdir}

for sub in ${subs}
do
	
sbatch ./single_sub_fmriprep.sh ${sub}

echo ‘done for subject: ‘ ${sub}
done

